### ISSUE TITLE
Readme Suggestions

### ISSUE THREAD

**Issue by deepikabhavnani** [OpenNuvoton/NuMaker-mbed-TZ-nonsecure-example#1]
Command for non-secure build is `mbed compile -m NUMAKER_PFM_M2351_NS -t ARMC6`, should we communicate users to use `NUMAKER_PFM_M2351` as default?

Background : Green tea test will fail with `NUMAKER_PFM_M2351_NS` unless --mock option is used with mbedls for target name.

Since target name by default is `NUMAKER_PFM_M2351` and that is for non-secure builds, shall we communicate the same in all documentation and avoid using _NS for target?

**Comment by cyliangtw** [comment]
NUMAKER_PFM_M2351 is implicit non-secure target, so we define NUMAKER_PFM_M2351_NS.
However to avoid confusion with Green tea test, it's OK to avoid _NS in documentation.
